name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

##############################################################

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # cancel-in-progress: true

permissions:
  contents: read

env:
  TURBO_API: http://127.0.0.1:9080
  TURBO_TOKEN: this-is-not-a-secret
  TURBO_TEAM: myself

##############################################################

jobs:
  ##############################################################

  install_dependencies:
    name: Setup
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: wyvox/action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo ${{ github.event.number }} > ./pr-number.txt

  ##############################################################

  lints:
    name: "Lint"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [install_dependencies]

    steps:
      - uses: wyvox/action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: pnpm lint

  ##############################################################

  node_tests:
    name: "Node Tests"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [install_dependencies]

    steps:
      - uses: wyvox/action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: pnpm turbo test:node

  browser_tests:
    name: "Browser Tests"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [install_dependencies]

    steps:
      - uses: wyvox/action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: pnpm turbo test:ember
